export const HEROES_PAGE_ENTER = '[HEROES PAGE] ENTER';
export const HEROES_SEARCH = '[HEROES PAGE] HEROES SEARCH';
export const HEROES_LOADED = '[HEROES PAGE] HEROES LOADED';
export const HEROES_LOAD_ERROR = '[HEROES PAGE] HEROES LOAD ERROR';
export const DETAIL_HERO_LOADED = '[DETAIL HERO PAGE] HERO LOADED FROM REMOTE';
export const DETAIL_HERO_ERROR = '[DETAIL HERO PAGE] REMOTE HERO LOAD ERROR';
